[package]
name = "bare"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv-rt = "0.6.1"
panic-halt = "0.2.0"

[[bin]]
name = "bare"
test = false
bench = false

[profile.release]
codegen-units = 1
debug = true
lto = true