[tasks.strip]
command = "riscv64-unknown-elf-strip"
args= [
    "target/riscv32imac-unknown-none-elf/release/wheely",
]

[tasks.objcopy]
command = "riscv64-unknown-elf-objcopy"
args= [
    "-O", "binary",
    "target/riscv32imac-unknown-none-elf/release/wheely",
    "target/riscv32imac-unknown-none-elf/release/wheely.bin"

]
dependencies = ["strip"]

[tasks.objdump]
command="riscv64-unknown-elf-objdump"
args = [
    "-d",
    "target/riscv32imac-unknown-none-elf/release/wheely"
]