name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
      - name: Setup Rust RiscV target
        run: rustup target add riscv32imac-unknown-none-elf
      - name: Setup GNU RiscV toolchain
        run:  apt install gcc-riscv64-unknown-elf
      - name: Compile rust source
        run: cd demo/empty; cargo build --release
      # - name: Compile
      #   run: sbt compile
